# Generated by Django 6.0.6 on 2026-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_ID', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cont_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('photo', models.FileField(null=True, upload_to='doctor_photo/')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
