# Generated by Django 6.0.6 on 2026-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cont_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('photo', models.FileField(null=True, upload_to='patient_photo/')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
