# Generated by Django 6.0.6 on 2026-06-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='patientID',
            new_name='patient_ID',
        ),
    ]
