# Generated by Django 6.0.6 on 2026-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_patientid_patientreg_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
