# Generated by Django 6.0.4 on 2026-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientreg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
