# Generated by Django 6.0.6 on 2026-07-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_doctorreg_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_ID', models.CharField(max_length=100, unique=True)),
                ('appointment_Date', models.DateField()),
                ('appointment_Time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.doctorreg', to_field='doctor_ID')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientreg', to_field='patient_ID')),
            ],
        ),
    ]
