# Generated by Django 6.0.6 on 2026-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreg',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='doctor_photo/'),
        ),
    ]
